// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Button': string;
  'Desktop': string;
  'LeftPanel': string;
  'Range': string;
}
export const cssExports: CssExports;
export default cssExports;
